name = "DividedRectangles"
uuid = "8f25b07e-6077-4668-9c5e-9c6bcc4ef962"
authors = ["Integra-Spec-A <Anshrin@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
